services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dblogin
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123abc
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=dblogin
    networks:
      - app-network
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge
